### ISSUE TITLE
Download to remote (FTP) storage

### ISSUE THREAD

**Issue by hiebra** [AndreyPavlenko/transmissionbtc#1]
I'm running the app from my Android TV box. It works perfect when my external hard disk is plugged and properly set up as device storage. I'd like to use a folder of my FTP server as download target. This would help me because I (as all Android users) have not too much internal storage and only one USB port. Another reason is that I'd like to be to format my disks in a portable way (android device storage is only valid for Android). Would this be a major change?

**Comment by AndreyPavlenko** [comment]
Support for FTP storage should be implemented in the transmission core, but not in the android app. If you really need this functionality, please resubmit this issue here -  https://github.com/transmission/transmission , but I doubt it will ever be implemented. I would recommend you either install transmission directly on your server, or use a different protocol instead of FTP - SMB or NFS, for example. On your android box you may mount a remote SMB or NFS folder and use it for downloads.

**Comment by hiebra** [comment]
Hi

Thank you for your response. I understand (for your words) that related code must be on the backed component. I've decided to attach a hard disk to my box forever (what is not so bad) but I'd like to note, to talk about an ideal future, that users of your wrapper have specific needs: We're not able to mount NFS/Samba content (except on rooted devices) and we are short of storage and USB ports. But such adaptation, I perfectly understand, could be difficult if the backed component's interface is not designed to be extended in that way. In any case I know too that there are more important issues than this one. If you prefer, I can send you future issues by mail before posting on GitHub

Greetings
________________________________

**Comment by AndreyPavlenko** [comment]
Sure, you can contact me by email.
